"""RTMX docs command for auto-generating documentation.

This module provides commands to generate documentation from rtmx internals:
- schema: Generate schema documentation from rtmx.schema module
- config: Generate configuration reference from RTMXConfig
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from rtmx import __version__
from rtmx.schema import CORE_SCHEMA, PHOENIX_EXTENSION, ColumnType, Schema, list_schemas


def _get_default_output_dir() -> Path:
    """Get the default output directory (.rtmx/cache/).

    Returns:
        Path to cache directory
    """
    cache_dir = Path.cwd() / ".rtmx" / "cache"
    cache_dir.mkdir(parents=True, exist_ok=True)
    return cache_dir


def _generate_header(title: str) -> str:
    """Generate document header with version and timestamp.

    Args:
        title: Document title

    Returns:
        Markdown header string
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""# {title}

> Generated by rtmx v{__version__} on {timestamp}

---

"""


def _format_column_type(col_type: ColumnType) -> str:
    """Format column type for display.

    Args:
        col_type: Column type enum

    Returns:
        Formatted type string
    """
    return col_type.value


def _generate_schema_section(schema: Schema) -> str:
    """Generate markdown documentation for a schema.

    Args:
        schema: Schema to document

    Returns:
        Markdown string
    """
    lines = [
        f"## {schema.name.title()} Schema",
        "",
        f"{schema.description}",
        "",
        "### Columns",
        "",
        "| Column | Type | Required | Default | Description |",
        "|--------|------|----------|---------|-------------|",
    ]

    for col in schema.columns.values():
        required = "Yes" if col.required else "No"
        default = f"`{col.default}`" if col.default != "" else "-"
        col_type = _format_column_type(col.type)
        description = col.description or "-"
        lines.append(f"| `{col.name}` | {col_type} | {required} | {default} | {description} |")

    lines.append("")
    return "\n".join(lines)


def _generate_column_types_section() -> str:
    """Generate documentation for column types.

    Returns:
        Markdown string
    """
    lines = [
        "## Column Types",
        "",
        "RTMX supports the following column data types:",
        "",
        "| Type | Description |",
        "|------|-------------|",
        "| `string` | Text value |",
        "| `integer` | Whole number |",
        "| `float` | Decimal number |",
        "| `boolean` | True/false value |",
        "| `date` | Date in YYYY-MM-DD format |",
        "| `list` | Pipe-separated values |",
        "",
    ]
    return "\n".join(lines)


def run_docs_schema(output: Path | None = None) -> None:
    """Generate schema documentation.

    Generates markdown documentation for all registered schemas including
    the core schema and Phoenix extension.

    Args:
        output: Output file path. If None, writes to .rtmx/cache/schema.md
    """
    if output is None:
        output = _get_default_output_dir() / "schema.md"
    else:
        output.parent.mkdir(parents=True, exist_ok=True)

    content = [_generate_header("RTMX Schema Reference")]

    # Overview
    content.append("## Overview\n")
    content.append("RTMX uses a flexible schema system that supports core requirements ")
    content.append("traceability fields plus optional extensions for specific use cases.\n\n")
    content.append(f"Available schemas: {', '.join(list_schemas())}\n\n")

    # Column types
    content.append(_generate_column_types_section())

    # Core schema
    content.append(_generate_schema_section(CORE_SCHEMA))

    # Phoenix extension
    content.append("## Phoenix Extension\n")
    content.append("The Phoenix extension adds validation taxonomy columns for scope, ")
    content.append("technique, and environment markers used in test-driven development.\n\n")
    content.append(_generate_schema_section(PHOENIX_EXTENSION))

    output.write_text("".join(content), encoding="utf-8")
    print(f"Schema documentation generated: {output}")


def _generate_config_section(
    name: str, description: str, fields: list[tuple[str, str, str]]
) -> str:
    """Generate markdown documentation for a config section.

    Args:
        name: Section name
        description: Section description
        fields: List of (field_name, type, description) tuples

    Returns:
        Markdown string
    """
    lines = [
        f"### {name}",
        "",
        description,
        "",
        "| Setting | Type | Description |",
        "|---------|------|-------------|",
    ]

    for field_name, field_type, field_desc in fields:
        lines.append(f"| `{field_name}` | {field_type} | {field_desc} |")

    lines.append("")
    return "\n".join(lines)


def _generate_yaml_example() -> str:
    """Generate example YAML configuration.

    Returns:
        Markdown code block with YAML example
    """
    return """## Example Configuration

```yaml
rtmx:
  database: docs/rtm_database.csv
  requirements_dir: docs/requirements
  schema: core

  pytest:
    marker_prefix: req
    register_markers: true

  agents:
    claude:
      enabled: true
      config_path: CLAUDE.md
    cursor:
      enabled: true
      config_path: .cursorrules
    copilot:
      enabled: true
      config_path: .github/copilot-instructions.md
    template_dir: .rtmx/templates/

  adapters:
    github:
      enabled: false
      repo: owner/repo
      token_env: GITHUB_TOKEN
      labels:
        - requirement
        - feature
      status_mapping:
        open: MISSING
        closed: COMPLETE
    jira:
      enabled: false
      server: https://your-domain.atlassian.net
      project: PROJECT
      token_env: JIRA_API_TOKEN
      email_env: JIRA_EMAIL
      issue_type: Requirement

  mcp:
    enabled: false
    port: 3000
    host: localhost

  sync:
    conflict_resolution: manual
```

"""


def run_docs_config(output: Path | None = None) -> None:
    """Generate configuration documentation.

    Generates markdown documentation for RTMXConfig showing all
    configuration options with their defaults and descriptions.

    Args:
        output: Output file path. If None, writes to .rtmx/cache/config.md
    """
    if output is None:
        output = _get_default_output_dir() / "config.md"
    else:
        output.parent.mkdir(parents=True, exist_ok=True)

    content = [_generate_header("RTMX Configuration Reference")]

    # Overview
    content.append("## Overview\n\n")
    content.append(
        "RTMX is configured via `rtmx.yaml` (legacy) or `.rtmx/config.yaml` (recommended).\n"
    )
    content.append("All settings are optional and have sensible defaults.\n\n")

    # Core settings
    content.append(
        _generate_config_section(
            "Core Settings",
            "Primary configuration options for rtmx.",
            [
                (
                    "database",
                    "Path",
                    "Path to RTM database CSV file. Default: `docs/rtm_database.csv`",
                ),
                (
                    "requirements_dir",
                    "Path",
                    "Directory for requirement specification files. Default: `docs/requirements`",
                ),
                ("schema", "string", "Schema to use (`core` or `phoenix`). Default: `core`"),
            ],
        )
    )

    # Pytest settings
    content.append(
        _generate_config_section(
            "Pytest Settings",
            "Configuration for pytest integration with requirement markers.",
            [
                ("marker_prefix", "string", "Prefix for requirement markers. Default: `req`"),
                ("register_markers", "boolean", "Auto-register custom markers. Default: `true`"),
            ],
        )
    )

    # Agents settings
    content.append(
        _generate_config_section(
            "Agents Settings",
            "Configuration for AI agent integrations (Claude, Cursor, Copilot).",
            [
                ("claude.enabled", "boolean", "Enable Claude integration. Default: `true`"),
                ("claude.config_path", "string", "Path to Claude config. Default: `CLAUDE.md`"),
                ("cursor.enabled", "boolean", "Enable Cursor integration. Default: `true`"),
                ("cursor.config_path", "string", "Path to Cursor config. Default: `.cursorrules`"),
                ("copilot.enabled", "boolean", "Enable Copilot integration. Default: `true`"),
                (
                    "copilot.config_path",
                    "string",
                    "Path to Copilot config. Default: `.github/copilot-instructions.md`",
                ),
                (
                    "template_dir",
                    "string",
                    "Directory for agent templates. Default: `.rtmx/templates/`",
                ),
            ],
        )
    )

    # Adapters settings
    content.append(
        _generate_config_section(
            "Adapters Settings",
            "Configuration for external service adapters (GitHub, Jira).",
            [
                ("github.enabled", "boolean", "Enable GitHub Issues sync. Default: `false`"),
                ("github.repo", "string", "GitHub repository (owner/repo)"),
                (
                    "github.token_env",
                    "string",
                    "Environment variable for GitHub token. Default: `GITHUB_TOKEN`",
                ),
                (
                    "github.labels",
                    "list",
                    "Labels for requirement issues. Default: `[requirement, feature]`",
                ),
                ("jira.enabled", "boolean", "Enable Jira sync. Default: `false`"),
                ("jira.server", "string", "Jira server URL"),
                ("jira.project", "string", "Jira project key"),
                (
                    "jira.token_env",
                    "string",
                    "Environment variable for Jira token. Default: `JIRA_API_TOKEN`",
                ),
                (
                    "jira.email_env",
                    "string",
                    "Environment variable for Jira email. Default: `JIRA_EMAIL`",
                ),
                (
                    "jira.issue_type",
                    "string",
                    "Jira issue type for requirements. Default: `Requirement`",
                ),
            ],
        )
    )

    # MCP settings
    content.append(
        _generate_config_section(
            "MCP Settings",
            "Configuration for MCP (Model Context Protocol) server.",
            [
                ("enabled", "boolean", "Enable MCP server. Default: `false`"),
                ("port", "integer", "Server port. Default: `3000`"),
                ("host", "string", "Bind address. Default: `localhost`"),
            ],
        )
    )

    # Sync settings
    content.append(
        _generate_config_section(
            "Sync Settings",
            "Configuration for synchronization behavior.",
            [
                (
                    "conflict_resolution",
                    "string",
                    "Conflict resolution strategy (`manual`, `prefer-local`, `prefer-remote`). Default: `manual`",
                ),
            ],
        )
    )

    # YAML example
    content.append(_generate_yaml_example())

    output.write_text("".join(content), encoding="utf-8")
    print(f"Config documentation generated: {output}")
