"""RTMX makefile command.

Generate Makefile targets for RTM commands.
"""

from __future__ import annotations

from pathlib import Path

MAKEFILE_TARGETS = """\
# RTMX - Requirements Traceability Matrix targets
# Generated by: rtmx makefile
# Add these targets to your project Makefile

.PHONY: rtm rtm-v rtm-vv rtm-vvv backlog backlog-critical cycles reconcile deps

## RTM Status Commands
rtm:  ## Show RTM summary status
\t@rtmx status

rtm-v:  ## Show RTM status by category
\t@rtmx status -v

rtm-vv:  ## Show RTM status by subcategory
\t@rtmx status -vv

rtm-vvv:  ## Show RTM status for all requirements
\t@rtmx status -vvv

## RTM Backlog Commands
backlog:  ## Show prioritized backlog
\t@rtmx backlog

backlog-critical:  ## Show critical path requirements only
\t@rtmx backlog --critical

# Usage: make backlog PHASE=1
ifneq ($(PHASE),)
backlog:
\t@rtmx backlog --phase $(PHASE)
endif

## RTM Analysis Commands
cycles:  ## Detect circular dependencies
\t@rtmx cycles

deps:  ## Show dependency graph
\t@rtmx deps

## RTM Maintenance Commands
reconcile:  ## Check dependency reciprocity (dry run)
\t@rtmx reconcile

reconcile-fix:  ## Fix dependency reciprocity issues
\t@rtmx reconcile --execute

## RTM Test Integration
from-tests:  ## Scan tests for requirement markers
\t@rtmx from-tests --all

from-tests-update:  ## Update RTM database from test markers
\t@rtmx from-tests --update
"""


def run_makefile(output: Path | None = None) -> None:
    """Run makefile command.

    Generates Makefile targets for RTM commands.

    Args:
        output: Output file path (None for stdout)
    """
    content = MAKEFILE_TARGETS

    if output:
        with output.open("w") as f:
            f.write(content)
        print(f"Generated Makefile targets in {output}")
        print()
        print("To use, add to your Makefile:")
        print(f"  include {output}")
        print()
        print("Or append to existing Makefile:")
        print(f"  cat {output} >> Makefile")
    else:
        print(content)
